SjMart/SjMart/urls.py
from django.contrib import admin
from django.urls import path,include
# from mart import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mart/',include('mart.urls')),
]

SjMart/mart/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name  = "mart"
urlpatterns = [
     path("",views.home,name='home'),
     path("products",views.goods,name='goods'),
     path("purchase",views.purchase,name='purchase'),
     path('buy/<int:brand_id>/', views.buy, name='buy'),
     path('sales',views.sales,name='sales'),
     path("suppliers",views.store_suppliers,name='suppliers'),
     path("staff",views.view_staff,name='staff'),
     path("shifts",views.staff_shifts,name='shifts'),
     path("model",views.model,name='model')

]
 

SjMart/mart/models.py
from django.db import models

class Acquisition(models.Model):
    brand_id = models.AutoField(primary_key=True)
    name = models.ForeignKey("name",on_delete=models.CASCADE,null=True)
    distr = models.ForeignKey('suppliers',null=True,on_delete=models.CASCADE)
    brand = models.CharField(max_length=45, null=True)
    price = models.IntegerField(null=True)
    quantity = models.IntegerField(null = True)
    


    def __str__(self):
        return self.brand 

class staff(models.Model):
    staff_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=255,null=True)
    last_name = models.CharField(max_length=255,null=True)
    job_cat = models.ForeignKey("job_categories",on_delete=models.CASCADE)
    email = models.EmailField(max_length=255,unique=True)
    phone_no = models.IntegerField()
    
    def __str__(self):
        return self.first_name


class job_categories(models.Model):
    cat_id = models.AutoField(primary_key=True)
    cat_name = models.CharField(max_length=255)

    def __str__(self):
        return self.cat_name

class shifts(models.Model):
    period = models.CharField(max_length=255)
    
    def __str__(self):
        return self.period
    

class suppliers(models.Model):
    supp_id = models.AutoField(primary_key=True)
    supp_name = models.CharField(max_length=30)
    email = models.EmailField()
    cell_one=models.CharField(max_length=20)
    cell_two=models.CharField(max_length=20)

    def __str__(self):
        return self.supp_name
    
    
class name(models.Model):
    name = models.CharField(max_length=255,null=True)

    def __str__(self):
        return self.name

class staff_in_shift(models.Model):
    shift=models.ForeignKey("shifts",on_delete=models.CASCADE,null=True)
    name=models.ForeignKey("staff",on_delete=models.CASCADE,null=True)
    Report_status=models.CharField(max_length=20)
    comments = models.CharField(max_length=100,null=True)

    # def __str__(self):
    #     return self.name

SjMart/mart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from .models import Acquisition,name,staff,job_categories,shifts,staff_in_shift,suppliers

def home(request):
    return render(request,"mart/home.html")

def goods(request):
    stock  = Acquisition.objects.all()
    context = {
        "objects":stock,
    }
    return render(request,"mart/goods.html",context)

def purchase(request):
    if request.method =='POST':
        category = request.POST.get('category')
        brand = request.POST.get('brand')
        qnty = request.POST.get('quantity')
        price = request.POST.get('price')
        dealer = request.POST.get('dealer')
        # contact = request.POST.get('contact')
        # getting the category name
        name_obj = name.objects.get(name=category)

        Acquisition.objects.create(brand = brand,price=price,quantity=qnty,distr=dealer,name=name_obj)
        return redirect('mart:goods')

    data = name.objects.all()
    distributer = suppliers.objects.all()
    context = {
        "data":data,
        "distr":distributer
    }
    return render(request,"mart/purchase.html",context)

def buy(request,brand_id):
    if request.method == 'POST':
        x=Acquisition.objects.get(pk = brand_id)
        order = request.POST.get('quantity')
        x.quantity +=int(order)
        x.save()
        return redirect("mart:goods")

        
    name = get_object_or_404(Acquisition,pk = brand_id)
    context = {
        "brand":name,
    }

    return render(request,'mart/buy.html',context)

def sales(request):
    stock  = Acquisition.objects.all()
    context = {
        "objects":stock,
    }

    if request.method=='POST':
        brand_name = request.POST.get('brand')
        qty = request.POST.get('quantity')
        try:
            brand_db = Acquisition.objects.get(brand=brand_name)
            if brand_db.quantity >= int(qty):
                brand_db.quantity -= int(qty)
                brand_db.save()
                return render(request,"mart/sales.html")
            else:
                return HttpResponse(f'Insufficient quantity for {brand_name}')
        except Acquisition.DoesNotExist:
            return HttpResponse(f'Brand not available: {brand_name}')
        
    

    return render(request,"mart/sales.html",context)

def store_suppliers(request):
    return render(request,'mart/suppliers.html')

def view_staff(request):
     # Get the job category object with the name 'corporate'
    corporate_category = job_categories.objects.get(cat_name='corporate')
    accountant_cat = job_categories.objects.get(cat_name = 'accountant')
    janitor_cat = job_categories.objects.get(cat_name = 'janitors')
    quality_cat = job_categories.objects.get(cat_name = 'Quality assurance')

    # Filter staff members by the corporate job category ID
    corporate_staff = staff.objects.filter(job_cat=corporate_category)
    accountant = staff.objects.filter(job_cat=accountant_cat)
    janitor = staff.objects.filter(job_cat=janitor_cat)
    quality = staff.objects.filter(job_cat=quality_cat)

    # You can also retrieve all staff members for other purposes
    all_staff = staff.objects.all()

    context = {
        "staff": all_staff,
        "corporate": corporate_staff,
        "accountant":accountant,
        "janitor":janitor,
        "quality":quality,
    }
    return render(request, 'mart/staff.html', context)

def staff_shifts(request):
    # early shift
    early_shift = shifts.objects.get(period='6am-12pm')
    early_staff = staff_in_shift.objects.filter(shift=early_shift)
    # mid shift
    mid_shift = shifts.objects.get(period='12pm-6pm')
    mid_staff = staff_in_shift.objects.filter(shift=mid_shift)
    # late shift
    late_shift = shifts.objects.get(period='6pm-11pm')
    late_staff = staff_in_shift.objects.filter(shift=late_shift)
    context = {
        "early":early_staff,
        "mid":mid_staff,
        "late":late_staff
    }
    return render(request,'mart/shifts.html',context)

def model(request):
    return render(request,"mart/model.html")
# Create your views here.

SjMart/mart/templates/mart/goods.html
<!DOCTYPE html>
<html>
    <head>
        <title>Shifts</title>
        {%load static%}
        <link rel="icon" type="image/png" href="{% static 'mart/images/favicon1.png' %}">
        <link rel="stylesheet" href="{% static 'mart/style.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <style>
          .custom-bg-color{
            background-color: #333;
          }
          .custom-bg-color .nav-link{
            color: white;
          }
          .custom-bg-color .nav-link img{
            width: 150px;
            height: 40px;
          }
          .sidebar {
              height: 150vh; /* Adjusted height */
              overflow-y: auto; /* Added to make the sidebar scrollable if content exceeds height */
          }
          
          .head {
              position: fixed;
              top: 0;
              width: 100%;
              padding: 20px;
              font-weight: 400;
              font-size: 1.4em;
              text-align: center;
              margin-top: -20px;
              background-color: white; /* Add a background color */
              z-index: 1; /* Set a higher z-index to keep it on top */
          }
          
  
          .head::first-letter{
            font-size: 1.5em;
            color: brown;
            font-size: 2em;
            font-weight: 1000;
          }
          .sidebar-sticky .nav-item a:hover{
            background-color: rgb(141, 120, 93);
          }
          .sidebar-sticky .nav-item a:active{
              background-color: rgb(141, 120, 93);
          }
          .container2 {
              display: flex;
              align-items: flex-start;
              height: 80vh;
          }
  
          .form-column {
              flex: 1;
              padding: 20px;
          }
  
          .image-column {
              flex: 1;
              padding: 20px;
          }
  
          .image {
              max-width: 100%;
              height: auto;
          }
          
          .footer {
              position: fixed;
              bottom: 0;
              width: 100%;
              background-color: white; /* Add a background color */
              padding: 10px 0;
              text-align: center;
              z-index: 1; /* Set a higher z-index to keep it on top */
          }
      </style>
    </head>
    <body>
<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block sidebar custom-bg-color">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="#"><img src="{% static 'mart/images/logo.png' %}"  alt="not found"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'mart:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:sales' %}">Sale</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:goods' %}">Stock</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:purchase' %}">Procument</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:suppliers' %}">Suppliers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:staff' %}">Staff</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:shifts' %}">Shifts</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <header class="head">SjMart Inc</header>
      <div style="margin-top: 90px;margin-bottom: 70px;">
        <h2>Stock</h2>
        <table class="table table-striped">
            <th>Brand Id</th>
            <th>Brand</th>
            <th>Stock Quantity</th>
            <th>Dealer</th>
            <th>Contact</th>
            <th>Price</th>
            <th>Order</th>
            {% for x in objects%}
            <tr>
                <td>{{x.brand_id}}</td>
                <td>{{x.brand}}</td>
                <td>{{x.quantity}}pcs</td>
                <td>{{x.d}}</td>
                <td>+254{{x.dealer_contact}}</td>
                <td>{{x.price}}Ksh</td>
                <td><a  href="{% url 'mart:buy' x.brand_id %}" style="font-size: 1.3em;color:darkslateblue;">order</a></td>
            </tr>
            {% endfor%}

        </table>
      </div>
      <div class="footer">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Contacts</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Products</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
        </ul>
        <p class="text-center text-muted">&copy; 2023 SjMart, Inc</p>
    </div>
      </div>
    </main>
  </div>
</div>

        
    </body>
</html>
{% comment %} <!DOCTYPE html>
<html>
    <head>
        <title>Products</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'mart/style.css' %}">
        <link rel="icon" type="image/png" href="{% static 'mart/images/favicon1.png' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link href="{% static 'mart/css/bootstrap.min.css' %}">
        <style>
            h2{
                margin-left: 20px;
                font-family: Arial, Helvetica, sans-serif;
                font-size: 1.3em;
                color: rgb(10, 44, 2);
            }
            body {
                margin: 0;
                padding: 0;
                font-family: Arial, sans-serif;
            }
    
            .navbar1 {
                overflow: hidden;
                background-color: #333;
            }
    
            .navbar1 a {
                float: left;
                font-size: 16px;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }
    
            .navbar1 a:hover {
                background-color: #ddd;
                color: black;
            }
    
            .logo {
                float: left;
                padding: 5px;
                margin-left: 10px;
            }
            table{
                margin-left: 10px;
            }
            h2{
                border-bottom: 2px solid ;
            }
            a{
                text-decoration: none;
            }
        </style>
        <script src="https://kit.fontawesome.com/479406705c.js" crossorigin="anonymous"></script> 
    </head>
    <body>
        <div class="navbar1">
            <div class="logo">
            <img src="{% static 'mart/images/logo.png' %}" alt="Logo"  height="50">
            </div>
            <a href="{% url 'mart:home' %}">Home</a>
            <a href="{% url 'mart:goods' %}">Products</a>
            <a href="{% url 'mart:purchase' %}">Purchases</a>
            <a href="{% url 'mart:sales' %}">Sales</a>
        </div>
        <h2 >Stock-in</h2>
        <table class="table table-striped">
            <th>Brand Id</th>
            <th>Brand</th>
            <th>Stock Quantity</th>
            <th>Dealer</th>
            <th>Contact</th>
            <th>Price</th>
            <th>Order</th>
            {% for x in objects%}
            <tr>
                <td>{{x.brand_id}}</td>
                <td>{{x.brand}}</td>
                <td>{{x.quantity}}pcs</td>
                <td>{{x.d}}</td>
                <td>+254{{x.dealer_contact}}</td>
                <td>{{x.price}}Ksh</td>
                <td><a  href="{% url 'mart:buy' x.brand_id %}" style="font-size: 1.3em;color:darkslateblue;">order</a></td>
            </tr>
            {% endfor%}

        </table>   
    </body>   
</html> {% endcomment %}

SjMart/mart/templates/mart/model.html
<!DOCTYPE html>
<html>
    <head>
        <title>Shifts</title>
        {%load static%}
        <link rel="icon" type="image/png" href="{% static 'mart/images/favicon1.png' %}">
        <link rel="stylesheet" href="{% static 'mart/style.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <style>
          .custom-bg-color{
            background-color: #333;
          }
          .custom-bg-color .nav-link{
            color: white;
          }
          .custom-bg-color .nav-link img{
            width: 150px;
            height: 40px;
          }
          .sidebar {
              height: 150vh; /* Adjusted height */
              overflow-y: auto; /* Added to make the sidebar scrollable if content exceeds height */
          }
          
          .head {
              position: fixed;
              top: 0;
              width: 100%;
              padding: 20px;
              font-weight: 400;
              font-size: 1.4em;
              text-align: center;
              margin-top: -20px;
              background-color: white; /* Add a background color */
              z-index: 1; /* Set a higher z-index to keep it on top */
          }
          
  
          .head::first-letter{
            font-size: 1.5em;
            color: brown;
            font-size: 2em;
            font-weight: 1000;
          }
          .sidebar-sticky .nav-item a:hover{
            background-color: rgb(141, 120, 93);
          }
          .sidebar-sticky .nav-item a:active{
              background-color: rgb(141, 120, 93);
          }
          .container2 {
              display: flex;
              align-items: flex-start;
              height: 80vh;
          }
  
          .form-column {
              flex: 1;
              padding: 20px;
          }
  
          .image-column {
              flex: 1;
              padding: 20px;
          }
  
          .image {
              max-width: 100%;
              height: auto;
          }
          
          .footer {
              position: fixed;
              bottom: 0;
              width: 100%;
              background-color: white; /* Add a background color */
              padding: 10px 0;
              text-align: center;
              z-index: 1; /* Set a higher z-index to keep it on top */
          }
      </style>
    </head>
    <body>
<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block sidebar custom-bg-color">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="#"><img src="{% static 'mart/images/logo.png' %}"  alt="not found"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'mart:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:sales' %}">Sale</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:goods' %}">Stock</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:purchase' %}">Procument</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:suppliers' %}">Suppliers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:staff' %}">Staff</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:shifts' %}">Shifts</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <header class="head">SjMart Inc</header>
      <table class="table table-striped" style="margin-top: 70px;">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td colspan="2">Larry the Bird</td>
            <td>@twitter</td>
          </tr>
        </tbody>
      </table>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          Dropdown button
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><a class="dropdown-item" href="#">Action</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
      </div>
      <div class="footer">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Contacts</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Products</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
        </ul>
        <p class="text-center text-muted">&copy; 2023 SjMart, Inc</p>
    </div>
      </div>
    </main>
  </div>
</div>

        
    </body>
</html>

SjMart/mart/templates/mart/purchase.html
<!DOCTYPE html>
<html>
    <head>
        <title>Shifts</title>
        {%load static%}
        <link rel="icon" type="image/png" href="{% static 'mart/images/favicon1.png' %}">
        <link rel="stylesheet" href="{% static 'mart/style.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <style>
        .custom-bg-color{
          background-color: #333;
        }
        .custom-bg-color .nav-link{
          color: white;
        }
        .custom-bg-color .nav-link img{
          width: 150px;
          height: 40px;
        }
        .sidebar {
            height: 100%%; /* Adjusted height */
            overflow-y: auto; /* Added to make the sidebar scrollable if content exceeds height */
        }
        
        .head {
            position: fixed;
            top: 0;
            width: 100%;
            padding: 20px;
            font-weight: 400;
            font-size: 1.4em;
            text-align: center;
            margin-top: -20px;
            background-color: white; /* Add a background color */
            z-index: 1; /* Set a higher z-index to keep it on top */
        }
        

        .head::first-letter{
          font-size: 1.5em;
          color: brown;
          font-size: 2em;
          font-weight: 1000;
        }
        .sidebar-sticky .nav-item a:hover{
          background-color: rgb(141, 120, 93);
        }
        .sidebar-sticky .nav-item a:active{
            background-color: rgb(141, 120, 93);
        }
        .container2 {
            display: flex;
            align-items: flex-start;
            height: 80vh;
        }

        .form-column {
            flex: 1;
            padding: 20px;
        }

        .image-column {
            flex: 1;
            padding: 20px;
        }

        .image {
            max-width: 100%;
            height: auto;
        }
        
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            background-color: white; /* Add a background color */
            padding: 10px 0;
            text-align: center;
            z-index: 1; /* Set a higher z-index to keep it on top */
        }
        p{
            border-bottom: 2px solid;
        }
      </style>
    </head>
    <body>
<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block sidebar custom-bg-color">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="#"><img src="{% static 'mart/images/logo.png' %}"  alt="not found"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'mart:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:sales' %}">Sale</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:goods' %}">Stock</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:purchase' %}">Procument</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:suppliers' %}">Suppliers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:staff' %}">Staff</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mart:shifts' %}">Shifts</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <header class="head" style="">SjMart Inc</header>
      <div style="margin-top: 70px;margin-bottom: 140px;">
        <div class="container2" style="height: 70%;">
            <div class="image-column">
                <img class="image" src="{% static 'mart/images/market.jpg' %}" alt="Image">
            </div>
            <div class="form-column">
                <p>New Brand Purchase</p>
                <form action="{% url 'mart:purchase' %}" method="post">
                    {% csrf_token %}
                    <label for="f" class="form-label">Category</label>
                    <select name="category" id="f" class="form-select" aria-label="Default select example">
                        {% for x in data%}
                        <option>{{x.name}}</option>
                        {%endfor%}
                    </select>
                    <label for="a" class="form-label">Brand</label>
                    <input type="text" id="a" name="brand" class="form-control" style="width: 100%;">
                    <label for="b" class="form-label">Quantity</label>
                    <input type="number" id="b" name="quantity" class="form-control">
                    <label for="c">Price</label><br>
                    <input type="number" id="c" name="price" class="form-control"><br>
                    <label for="d" class="form-label">Distributer</label><br>
                    <select name="dealer" id="d" class="form-select" aria-label="Default select example">
                        {% for x in distr%}
                        <option>{{x.supp_name}}</option>
                        {%endfor%}
                    </select><br>
                    <label for="e" class="form-label">Contact info</label><br>
                    <input type="text" id="e" name="contact" class="form-control" style="width: 100%;"><br><br>
                    <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
                </form>
            </div>
            
        </div>
      </div>
      <div class="footer">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Contacts</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Products</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
        </ul>
        <p class="text-center text-muted">&copy; 2023 SjMart, Inc</p>
    </div>
    </main>
  </div>
</div>

        
    </body>
</html>